#!/bin/sh /etc/rc.common
# Hybrid Failover Core: routing + policy monitor (procd)

START=99
STOP=10
USE_PROCD=1

start_service() {
	/usr/sbin/hybrid-failover start

	procd_open_instance
	procd_set_param command /usr/sbin/hybrid-failover monitor
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	/usr/sbin/hybrid-failover stop
}

reload_service() {
	/usr/sbin/hybrid-failover reload
}

status() {
	/usr/sbin/hybrid-failover status
}
